### ISSUE TITLE
PokerSNES and Snes9x

### ISSUE THREAD

**Issue by Johnny56732** [retrogamehandheld/OpenDingux#7]
Tenshi no Uta - Shiroki Tsubasa no Inroi           
Song of the Angel English translation 
No txt appearing at all in the game
When you play the japanese game everything works fine & if I could read Japanese I'd be ok lol
BS Zelda no Densetsu 3rd quest
Unplayable on pocketsnes
Snes9x no full screen
The option to select full screen doesn't work

**Comment by GldRush98** [comment]
PocketSNES - ActRaiser is broken on everything but the Japanese versions. Scrambled audio and the game will usually just freeze at the end of the first level.

**Comment by gladel** [comment]
Add hardware fullscreen scaling to Snes9x.

**Comment by gladel** [comment]
Gong sounds keep repeating and lingering in every Mortal Kombat game on PocketSNES.

**Comment by GldRush98** [comment]
This repo has absolutely nothing to do with PocketSNES or Snes9x development.  Your posts are falling on deaf ears.  This repo is simply a list of apps that run on RG's OpenDingux devices. No development work is happening here. You will need to report these issues to the individual app's authors.

**Comment by Jakz** [comment]
Closing as unrelated to the repository.
